spring:
  application:
   name: firstSampleService
  profiles:
    active: dev
    

    
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    register-with-eureka: true # \uc720\ub808\uce74 \uc11c\ube44\uc2a4\uc5d0 (\uc790\uc2e0\uc744) \ub4f1\ub85d \uc5ec\ubd80
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.0.46:8761/eureka/
  
myconfig:
  value: jhpark222



